// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbdsiqajsmcluvhfwqeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiZHNpcWFqc21jbHV2aGZ3cWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTg4MTQsImV4cCI6MjA1OTg5NDgxNH0.GQyARYmpQFU4K3WoULdGL-5Tk494d7EgQshdL7BZjEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);